#! /bin/bash

ml CMake
ml GCC
export OMP_NUM_THREADS=128
cmake -S. -Bbuild
cmake --build build
for j in compact scatter balanced none; do
    export KMP_AFFINITY=granularity=fine, $j
    for i in `seq 1 10`; do
        ./build/main $1 | grep "Time" | awk '{print $type, $2, $4}' >> omp_scaling_test_results
    done
done
